import { env } from './env'

export const FEATURES = {
  ENABLE_DEVELOPER_DNA: env.ENABLE_DEVELOPER_DNA !== 'false',
  ENABLE_RESUME_BUILDER: env.ENABLE_RESUME_BUILDER !== 'false',
  ENABLE_PORTFOLIO_GENERATOR: env.ENABLE_PORTFOLIO_GENERATOR !== 'false',
  ENABLE_SOCIAL_SHARING: env.ENABLE_SOCIAL_SHARING !== 'false',
  ENABLE_GITHUB_WRAPPED: env.ENABLE_GITHUB_WRAPPED !== 'false',
  ENABLE_REPO_COMPARE: env.ENABLE_REPO_COMPARE !== 'false',
  ENABLE_PUBLIC_PROFILES: env.ENABLE_PUBLIC_PROFILES !== 'false',
  ENABLE_BACKGROUND_JOBS: env.ENABLE_BACKGROUND_JOBS !== 'false',
} as const

export type FeatureKey = keyof typeof FEATURES
